name: Wakatime Charts

on:
  workflow_dispatch:
  schedule:
    - cron: "* */3 * * *"

jobs:
  update-charts:
    name: Update wakatime stats charts
    runs-on: ubuntu-latest
    steps:
      - uses: divykj/wakatime-charts@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: "âœ… images build success"
          BRANCH_NAME: "main"
          IMAGES_FOLDER: "images"
          GITHUB_TOKEN: ${{ github.token }}
